version: 2
jobs:
  build:
    executorType: docker
    containerInfo:
      - image: clojure:lein-2.7.1
    workDir: /
    steps:
      - type: checkout

      - type: shell
        command: echo YAY!
