version: 2
jobs:
  build:
    executorType: docker
    containerInfo:
      - image: buildpack-deps:jessie-curl
    workDir: /
    steps:
      - type: checkout

      - type: shell
        command: echo YAY!
