version: 2
jobs:
  build:
    executorType: docker
    containerInfo:
      - image: alpine:3.5
    workDir: /
    steps:
      - type: checkout

      - type: shell
        shell: sh
        command: echo YAY!
