version: 2
jobs:
  build:
    executorType: docker
    containerInfo:
      - image: clojure:lein-2.7.1
      - image: postgres:9.3-alpine
        env:
          - POSTGRES_USER=root
          - POSTGRES_DB=test
          
    workDir: ~/suricatta
    steps:
      - type: checkout

      - type: shell
        command: lein test-all
