version: 2
jobs:
  build:
    docker:
      - image: clojure:lein-2.7.1
      - image: postgres:9.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: test

    working_directory: ~/suricatta
    steps:
      - checkout

      - restore_cache:
          key: v1-jars-{{ checksum "project.clj" }}

      - run:
          name: loop
          command: | 
            for number in {1..1000}
            do
              sleep 1
              echo "$number "
            done

      - save_cache:
          key: v1-jars-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

      - store_artifacts:
          path: test2junit

      - store_test_results:
          path: test2junit/xml
